### PR TITLE
Adding support for switchable HTTP Clients

### PR DESCRIPTION
**Pull request by guusvw**

### CODE REVIEW

**Comment by beckjake** [comment]
Hi @guusvw, thanks for your contribution!

I'm sorry this has sat for so long, we do not frequently check our github repositories for PRs.

Can you please clarify on what a user would have to do to make use of this code? It appears to me that someone importing the jcapi package would need to set `jcapi.HTTPClientFn` to their own custom value, is that accurate?

**Comment by antonu17** [comment]
Hi @guusvw, @beckjake!
As I see, the main problem is that V1 API libray does not allow to set a timeout on API calls. There is an article explaining the problem: https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
And this patch makes it possible to provide custom http.Client (with timeout configured, for instance).
I tried this out like this:

	jcapi.HTTPClientFn = func(_ context.Context) *http.Client {
		return &http.Client{
			Transport: myTransport,
			Timeout:   myTimeout,
		}
	}
	jcAPIv1 := jcapi.NewJCAPI(myAPIKey, jumpCloudAPIURL)

And it worked as expected. The only thing unclear here is introducing a context, which is not used anywhere. But it can be kindly ignored :smiley: 
Is it possible to merge this PR so users don't have to fork it and implement timeouts on client side?

**Comment by beckjake** [comment]
Hi Anton,

That is a good reason and I'd do it if I could, but unfortunately I no
longer work at JumpCloud. I'm not sure anyone who works there really looks
at these things at all unfortunately, Github makes it pretty invisible and
I recall only seeing the original issue because I explicitly was looking
through our open issues/PRs on this repository.

You might have better luck escalating through support or whoever manages
your account, or something like that. Sorry I can't help!

**Comment by gregorykeller** [comment]
Anton - we do review these and in fact our API PM is handling the review
now. We'll get back to you soon.

Greg


*Greg Keller*
Chief Product Officer
greg.keller@jumpcloud.com
303.668.8277

<https://jumpcloud.com/> [image: linkedin]
<https://www.linkedin.com/company/jumpcloud>[image: facebook]
<https://www.facebook.com/JumpCloud.DaaS/>[image: twitter]
<https://twitter.com/jumpcloud>[image: blog] <https://jumpcloud.com/blog/>

The information transmitted is intended only for the person to whom it is
addressed and may contain confidential material. Review or other use of
this information by persons other than the intended recipient is
prohibited. If you've received this in error, please contact the sender and
delete from any computer.
Something you'd like to see included in the product?  Submit a feature
request <https://support.jumpcloud.com/customer/portal/questions/new>

**Comment by jpvajda** [comment]
@antonu17 Hello! I'm reviewing this PR now with a few of our Engineers here at Jumpcloud. We are focusing more attention on our SDKs now as a company, so I apologize for the delays you've had in the past.  We'll let you know if there are any questions / comments on this PR shortly.

**Comment by jpvajda** [comment]
@antonu17 we just updated our JCAPI Go Library to support v1 endpoints. I'm curious if you can use that SDK for your needs, instead of needing this PR merged into this SDK Library. We have technically discontinued support on JCAPI as it's out dated with our current set of API functionality. Just let me know if this option works for you or if you still need this PR merged into this older library.

https://github.com/TheJumpCloud/jcapi-go

**Comment by antonu17** [comment]
Ah, perfect. Thank you for the update, @jpvajda. I'm gonna switch on it now!

**Comment by jpvajda** [comment]
Closing PR as customer is switching to the new JCAPI-Go client.

**Pull request closed without merging**
